### ISSUE TITLE
Using Scala classes

### ISSUE THREAD

**Issue by joshuasiler** [cscotta/Octobot#2]
I've got octobot all up and running, but I'm having a hard time getting it to load my tasks. Specifically, they're Scala classes... am I missing something? I've got them packaged up in a jar as described by the docs, but they don't seem to be getting picked up. Are there more steps involved if I want to use Scala tasks?

**Comment by cscotta** [comment]
Hi Joshua,

Scala should work just fine (I know of someone actively using the two together in production without incident).

This sounds like a classpath / packaging issue.  If you're using the included "./octobot" script to launch it while inside the base directory, it expects to find a file called "tasks.jar" right alongside the launch script.

When the task is sent in as JSON, the task name needs to be the fully-qualified class name (e.g., "task": "com.eatenbyagrue.YourClassName", or tasks.YourClassName, depending on how you package it) - at least as specified in the package, assuming it's been jar'd correctly as well.  If there were an error, you might see one of the following messages:

"Error: Task requested not found."
"Error: Task requested does not have a static run method."
"An error occurred while running the task."

If a task with the fully-qualified class name specified in the JSON does not exist, you'll see the first. If it's not set up properly, you'll see the second. If an unhandled exception was thrown inside the task's code, you'll see the third.  Which of these are you seeing?

Additionally, if this doesn't help and you'd like to attach a stripped-out version of the Scala task you're trying to execute, I'd be happy to check it out and see what's up.

[ Also, I've been on a Scala kick lately. Check this out if you're curious - http://github.com/cscotta/Octobot-Scala - it's not ready quite yet, but is nearly complete. ]
- Scott

**Comment by joshuasiler** [comment]
Thanks for the reply. I'm using the octobot jar running script, and I've verified that it can find my tasks jar. Still not working :(  In any case, I'm starting to think it might be better to just include the queue polling functionality directly in the app. I'll definitely take a closer look at your Scala version... are you using 2.8 or 2.7?

**Comment by cscotta** [comment]
The Scala version targets 2.8 as it uses the new implicit JavaConversions support to pass messages to tasks written in about any other JVM language. It's pretty much production-ready; let me know if you have any questions it.

You mentioned that it sees the jar, but didn't mention which error you're seeing; I'll assume it was "Task requested not found." I'd really like to help you figure this out, even if you end up deciding to go the other direction, for the benefit of anyone else who might run into it.

One other possible thing to consider - I hadn't thought of this before, but if you bundle your tasks into a tasks.jar, but do not include any other libraries that those tasks depend on, there's a decent chance that a NoClassDefFound error could be thrown, which would cause this error to be raised.  In that case, it would be good to make sure that all of the libraries that tasks.jar was compiled against (including scala-library.jar, and any others) are in the classpath by editing the launch script and adding tasks.jar:scala-library.jar, colon-separated, along with any others to the line specifying the classpath (either MY_TASKS if you're using the special launch script, or just by specifying the classpath as you normally would otherwise).  I'd forgotten that the scala-library needs to be referenced or bundled into the tasks jar.

If you wouldn't mind posting a gist of your sample, I'd love to help you figure this out regardless!  Noticed you're in PDX as well - if you're up for figuring it out over a cup of coffee, that's fine too.

– Scott

**Comment by joshuasiler** [comment]
Hmm... you know I'm pretty sure it was a dependency issue with the scala-library jar. In any case, I ended up spending too much time on it, and went ahead and implemented a Rabbit consumer directly into my app. 

I'd love to take you up on your offer to hook up for a cup of coffee - be good to talk to others working with Scala. I'll drop you an email...
- Josh

**Comment by matthiase** [comment]
I realize this is an old discussion, but I ran into the same issue (Octobot is unable to find tasks when using octobot-jar) and I figured someone else may find this useful.  The solution I came up with is to modify the manifest in build.xml to specify the class path:

``` xml
<manifest file="MANIFEST.MF">
    <attribute name="Built-By" value="${user.name}"/>
    <attribute name="Class-Path" value="../tasks.jar" />
    <attribute name="Main-Class" value="com.urbanairship.octobot.Octobot"/>
</manifest>
```

Apparently, passing the -cp parameter to the java command when launching a self-executing jar is not enough.  I'm not really a Java programmer and I could be totally wrong about that.  Anyway, this works for me.

P.S. Thanks for creating Octobot... it looks pretty awesome.
